# Generated by Django 3.2.9 on 2021-11-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisaRegistration', '0002_country_visa_visastatus_visatariff_visatype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='VisaCountry',
        ),
    ]
